pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm // Récupère le code source du dépôt configuré dans Jenkins
            }
        }

        stage('Build and Test') {
            steps {
                sh 'mvn clean test'
            }
        }

    }

    post {
        success {
            echo 'Build and tests succeeded BROOOOO !'
        }
        failure {
            echo 'Build or tests failed!'
        }
    }
}
